export const BANGKOK_DISTRICTS = [
  'Phra Nakhon',
  'Dusit',
  'Nong Chok',
  'Bang Rak',
  'Bang Khen',
  'Bang Kapi',
  'Pathum Wan',
  'Pom Prap Sattru Phai',
  'Phra Khanong',
  'Min Buri',
  'Lat Krabang',
  'Yan Nawa',
  'Samphanthawong',
  'Phaya Thai',
  'Thon Buri',
  'Bangkok Yai',
  'Huai Khwang',
  'Khlong San',
  'Taling Chan',
  'Bangkok Noi',
  'Bang Khun Thian',
  'Phasi Charoen',
  'Nong Khaem',
  'Rat Burana',
  'Bang Phlat',
  'Din Daeng',
  'Bueng Kum',
  'Sathon',
  'Bang Sue',
  'Chatuchak',
  'Bang Kho Laem',
  'Prawet',
  'Khlong Toei',
  'Suan Luang',
  'Chom Thong',
  'Don Mueang',
  'Ratchathewi',
  'Lat Phrao',
  'Watthana',
  'Bang Khae',
  'Lak Si',
  'Sai Mai',
  'Khan Na Yao',
  'Saphan Sung',
  'Wang Thonglang',
  'Khlong Sam Wa',
  'Bang Na',
  'Thawi Watthana',
  'Thung Khru',
  'Bang Bon',
] as const

export type BangkokDistrict = (typeof BANGKOK_DISTRICTS)[number]
