import type { Patient, MedicalHistory, Appointment, Treatment } from "./types"

// Mock patient data
export const mockPatients: Patient[] = [
  {
    id: "p1",
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "1985-06-15",
    gender: "male",
    phoneNumber: "+1-555-0123",
    email: "john.doe@email.com",
    address: "123 Main St, Springfield, IL 62701",
    emergencyContact: {
      name: "Jane Doe",
      relationship: "Spouse",
      phoneNumber: "+1-555-0124",
    },
    bloodType: "O+",
    allergies: ["Penicillin", "Shellfish"],
    chronicConditions: ["Hypertension"],
    currentMedications: ["Lisinopril 10mg"],
    patientId: "PAT-001",
    registrationDate: "2024-01-15",
    lastVisit: "2024-12-20",
    assignedDoctor: "2",
    assignedCaregiver: "4",
    assignedVHV: "5",
    riskLevel: "medium",
    priority: false,
    district: "District A",
    village: "Springfield",
    householdId: "HH-001",
  },
  {
    id: "p2",
    firstName: "Maria",
    lastName: "Garcia",
    dateOfBirth: "1992-03-22",
    gender: "female",
    phoneNumber: "+1-555-0456",
    address: "456 Oak Ave, Springfield, IL 62702",
    emergencyContact: {
      name: "Carlos Garcia",
      relationship: "Father",
      phoneNumber: "+1-555-0457",
    },
    bloodType: "A-",
    allergies: [],
    chronicConditions: ["Diabetes Type 2"],
    currentMedications: ["Metformin 500mg"],
    patientId: "PAT-002",
    registrationDate: "2024-02-10",
    lastVisit: "2024-12-18",
    assignedDoctor: "2",
    riskLevel: "high",
    priority: true,
    district: "District A",
    village: "Springfield",
    householdId: "HH-002",
  },
]

export const mockMedicalHistory: MedicalHistory[] = [
  {
    id: "mh1",
    patientId: "p1",
    date: "2024-12-20",
    type: "visit",
    title: "Routine Check-up",
    description:
      "Annual physical examination. Blood pressure elevated at 145/90. Recommended lifestyle changes and medication adjustment.",
    doctorId: "2",
    doctorName: "Dr. Sarah Smith",
    followUpRequired: true,
    followUpDate: "2025-01-20",
  },
  {
    id: "mh2",
    patientId: "p2",
    date: "2024-12-18",
    type: "treatment",
    title: "Diabetes Management",
    description: "HbA1c levels at 8.2%. Adjusted Metformin dosage and provided dietary counseling.",
    doctorId: "2",
    doctorName: "Dr. Sarah Smith",
    followUpRequired: true,
    followUpDate: "2025-01-15",
  },
]

export const mockAppointments: Appointment[] = [
  {
    id: "apt1",
    patientId: "p1",
    patientName: "John Doe",
    doctorId: "2",
    doctorName: "Dr. Sarah Smith",
    date: "2025-01-20",
    time: "10:00",
    type: "follow_up",
    status: "scheduled",
    priority: "medium",
  },
  {
    id: "apt2",
    patientId: "p2",
    patientName: "Maria Garcia",
    doctorId: "2",
    doctorName: "Dr. Sarah Smith",
    date: "2025-01-15",
    time: "14:30",
    type: "follow_up",
    status: "scheduled",
    priority: "high",
  },
]

export const mockTreatments: Treatment[] = [
  {
    id: "t1",
    patientId: "p1",
    doctorId: "2",
    date: "2024-12-20",
    diagnosis: "Essential Hypertension",
    treatment: "Lifestyle modification and medication adjustment",
    medications: [
      {
        name: "Lisinopril",
        dosage: "15mg",
        frequency: "Once daily",
        duration: "Ongoing",
      },
    ],
    instructions: "Monitor blood pressure daily. Reduce sodium intake. Exercise 30 minutes daily.",
    followUpRequired: true,
    followUpDate: "2025-01-20",
    status: "active",
  },
]
