-- Fix intake_submissions table ID column to use TEXT type instead of UUID
-- This allows compatibility with CUID format IDs generated by the application

DO $$ 
BEGIN
  -- Check if table exists and column is not already TEXT
  IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'intake_submissions') THEN
    -- Check if column type needs to be changed
    IF EXISTS (
      SELECT 1 FROM information_schema.columns 
      WHERE table_schema = 'public' 
      AND table_name = 'intake_submissions' 
      AND column_name = 'id' 
      AND data_type != 'text'
    ) THEN
      ALTER TABLE public.intake_submissions
      ALTER COLUMN id TYPE TEXT;
    END IF;
  END IF;
END $$;